name: Westernport IT
favicon: null
layout_spectrum: 0.28659
typography_spectrum: 0.23448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#333333'
    - '#666666'
    - '#cacaca'
    - '#28abe3'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
